version: '3.9'

services:
  app:
    build: .
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=role-helper
      - POSTGRES_PASSWORD=role-helper
      - POSTGRES_DB=role-helper
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"